// <auto-generated />
using System;
using DataLayer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20200625114032_ProfessorsAndSubjectsAdded")]
    partial class ProfessorsAndSubjectsAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStudentOnLecture")
                        .HasColumnType("bit");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("DataLayer.Entities.Professor", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfessorId");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            ProfessorId = 1,
                            Name = "Victor",
                            Surname = "Vtorov"
                        },
                        new
                        {
                            ProfessorId = 2,
                            Name = "Anastasiia",
                            Surname = "Stotskaya"
                        },
                        new
                        {
                            ProfessorId = 3,
                            Name = "Eduard",
                            Surname = "Chernishov"
                        },
                        new
                        {
                            ProfessorId = 4,
                            Name = "Alexander",
                            Surname = "Zubarev"
                        },
                        new
                        {
                            ProfessorId = 5,
                            Name = "Andrey",
                            Surname = "Weinmeister"
                        },
                        new
                        {
                            ProfessorId = 6,
                            Name = "Mikhail",
                            Surname = "Kopichev"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Name = "Vladislav",
                            Surname = "Kruzhkov"
                        },
                        new
                        {
                            StudentId = 2,
                            Name = "Ferre",
                            Surname = "Dezutter"
                        },
                        new
                        {
                            StudentId = 3,
                            Name = "Ivan",
                            Surname = "Ivanov"
                        },
                        new
                        {
                            StudentId = 4,
                            Name = "Petr",
                            Surname = "Petrov"
                        },
                        new
                        {
                            StudentId = 5,
                            Name = "Anton",
                            Surname = "Antonov"
                        },
                        new
                        {
                            StudentId = 6,
                            Name = "Alexander",
                            Surname = "Enotov"
                        },
                        new
                        {
                            StudentId = 7,
                            Name = "Kirill",
                            Surname = "Ofitserov"
                        },
                        new
                        {
                            StudentId = 8,
                            Name = "Egor",
                            Surname = "Sorokin"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Name = "Control Systems",
                            ProfessorId = 1
                        },
                        new
                        {
                            SubjectId = 7,
                            Name = "Adaptive And Nonlinear Systems",
                            ProfessorId = 1
                        },
                        new
                        {
                            SubjectId = 2,
                            Name = "LabView",
                            ProfessorId = 2
                        },
                        new
                        {
                            SubjectId = 3,
                            Name = "Electrical Engineering",
                            ProfessorId = 3
                        },
                        new
                        {
                            SubjectId = 4,
                            Name = "TOE",
                            ProfessorId = 4
                        },
                        new
                        {
                            SubjectId = 5,
                            Name = "History",
                            ProfessorId = 5
                        },
                        new
                        {
                            SubjectId = 6,
                            Name = "Microcontrollers",
                            ProfessorId = 6
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Attendance", b =>
                {
                    b.HasOne("DataLayer.Entities.Student", "Student")
                        .WithMany("Attendance")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.Subject", "Subject")
                        .WithMany("Attendance")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Entities.Subject", b =>
                {
                    b.HasOne("DataLayer.Entities.Professor", "Professor")
                        .WithMany("Subjects")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
