// <auto-generated />
using System;
using DataLayer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20200625121944_FullDefaultBase")]
    partial class FullDefaultBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStudentOnLecture")
                        .HasColumnType("bit");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Attendance");

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 2,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 3,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 4,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 5,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 6,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 7,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 8,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 3,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 9,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 2,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 10,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 1,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 11,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 12,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 13,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 14,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 15,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 16,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 17,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 18,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 19,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 20,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 21,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 22,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 23,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 24,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 25,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 26,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 27,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 28,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 29,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 30,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 31,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 32,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 33,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 34,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 35,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 36,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 37,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 38,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 39,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 40,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 41,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 42,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 43,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 44,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 45,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 46,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 47,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 48,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 3,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 49,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 2,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 50,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 1,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 51,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 52,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 53,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 54,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 55,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 56,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 57,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 58,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 59,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 60,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 0,
                            StudentId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 61,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 62,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 63,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 64,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 65,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 66,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 67,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 68,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 3,
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 69,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 2,
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 70,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 1,
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 71,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 1,
                            StudentId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 72,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 2,
                            StudentId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 73,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 3,
                            StudentId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 74,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 4,
                            StudentId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 75,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 76,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 77,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 78,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 79,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 80,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = true,
                            Mark = 5,
                            StudentId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 81,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 82,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 83,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 84,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 85,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            AttendanceId = 86,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 87,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 88,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 89,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 90,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            AttendanceId = 91,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 92,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 93,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 94,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 95,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            AttendanceId = 96,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 97,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 98,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 99,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            AttendanceId = 100,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsStudentOnLecture = false,
                            Mark = 0,
                            StudentId = 5,
                            SubjectId = 4
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Professor", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfessorId");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            ProfessorId = 1,
                            Name = "Victor",
                            Surname = "Vtorov"
                        },
                        new
                        {
                            ProfessorId = 2,
                            Name = "Anastasiia",
                            Surname = "Stotskaya"
                        },
                        new
                        {
                            ProfessorId = 3,
                            Name = "Eduard",
                            Surname = "Chernishov"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Name = "Vladislav",
                            Surname = "Kruzhkov"
                        },
                        new
                        {
                            StudentId = 2,
                            Name = "Ferre",
                            Surname = "Dezutter"
                        },
                        new
                        {
                            StudentId = 3,
                            Name = "Ivan",
                            Surname = "Ivanov"
                        },
                        new
                        {
                            StudentId = 4,
                            Name = "Petr",
                            Surname = "Petrov"
                        },
                        new
                        {
                            StudentId = 5,
                            Name = "Anton",
                            Surname = "Antonov"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Name = "Control Systems",
                            ProfessorId = 1
                        },
                        new
                        {
                            SubjectId = 4,
                            Name = "Adaptive And Nonlinear Systems",
                            ProfessorId = 1
                        },
                        new
                        {
                            SubjectId = 2,
                            Name = "LabView",
                            ProfessorId = 2
                        },
                        new
                        {
                            SubjectId = 3,
                            Name = "Electrical Engineering",
                            ProfessorId = 3
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Attendance", b =>
                {
                    b.HasOne("DataLayer.Entities.Student", "Student")
                        .WithMany("Attendance")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.Subject", "Subject")
                        .WithMany("Attendance")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Entities.Subject", b =>
                {
                    b.HasOne("DataLayer.Entities.Professor", "Professor")
                        .WithMany("Subjects")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
